
services:
  postgres:
    image: postgres
    container_name: postgres-cbrcurrency
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - cbrcurrency-network

  dind:
    image: docker:24-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-storage:/var/lib/docker
    networks:
      - cbrcurrency-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cbrcurrency
    depends_on:
      - postgres
      - dind
    ports:
      - "8080:8080"
    networks:
      - cbrcurrency-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cbrcurrency:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - cbrcurrency-network


volumes:
  pgdata:
  dind-storage:

networks:
  cbrcurrency-network: