services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/your_database_name
      - DATABASE_USER=your_database_user
      - DATABASE_PASSWORD=your_database_password
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
      - POSTGRES_DB=your_database_name