spring:
  application:
    name=cbrcurrency

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  task:
    scheduling:
      pool:
        size: 1
logging:
  level:
    ru.andreymerkulov.cbrcurrency: DEBUG

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

cbr:
  api-url: https://www.cbr-xml-daily.ru/daily_json.js