spring:
  application:
    name=cbrcurrency

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  task:
    scheduling:
      pool:
        size: 1
  logging:
    level:
      ru.andreymerkulov.cbrcurrency: DEBUG

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cbr:
  api-url: https://www.cbr-xml-daily.ru/daily_json.js

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, info
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#        step: 1h