name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and test
        run: ./mvnw clean install -DskipTests=false

  build-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build Docker image
        run: docker-compose build

#      - name: Save Docker image as tar archive
#        run: docker save docker.io/library/cbrcurrency_app -o cbrcurrency.tar
#
#      - name: Save Docker image as artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: cbrcurrency-service-image
#          path: cbrcurrency.tar

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GHCR_TOKEN }}
          default_bump: patch #  0.0.0 -> 0.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push the Docker image
        run: |
          docker tag cbrcurrency:latest ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.tag_version.outputs.new_tag }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.tag_version.outputs.new_tag }}