name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and test
        run: ./mvnw clean install -DskipTests=false

  build-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SC_VM_IP_ADDRESS }}
          username: ${{ secrets.SC_VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.SC_VM_USERNAME }}/app"

      - name: Execute Docker Compose on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SC_VM_IP_ADDRESS }}
          username: ${{ secrets.SC_VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SC_VM_USERNAME }}/app 
            docker-compose pull  
            docker-compose down  
            docker-compose up -d